language: rust

# Recommeneded caching strategy from https://levans.fr/rust_travis_cache.html
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

env: # required for allow_failures
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  include:
    - rust: stable
      env: NAME='linting'
      before_script:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cargo fmt --all -- --check
        - cargo clippy

script: |
  export RUST_BACKTRACE=1 &&
  cargo build --verbose &&
  cargo test --verbose &&
  cargo doc --no-deps --verbose
